package me.FlyingHalfMast.events;

public class Chat {

	/* IF USER'S INFORMATION DOES NOT EXIST IN HASHMAP, CREATE IT
	 * IF IT DOES, UPDATE THE HASHMAP TO DELETE AND/OR REPLACE THE LINE
	 * WITH THE NEW CHARACTER'S INFORMATION
	 * SHOULDN'T BE PROBLEM WHEN LOADING FOR NEW USER BECAUSE IT CHECKS THE NEW USER'S FIRST ITEM IN LIST
	 * SO THIS WILL WORK EVEN IF PLAYER ONLY HAS ONE CHARACTER
	 */ 
	
}
